{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "rsync",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "rsync",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "rsync",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "rsync",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-09-03T18:10:00Z",
  "bugzilla": {
    "description": "CVE-2020-14387 rsync:  rsync-ssl does not verify the hostname in the server certificate when using openssl",
    "id": "1875549",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1875549"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "CWE-297",
  "statement": "",
  "acknowledgement": "Red Hat would like to thank Matt McCutchen for reporting this issue.",
  "name": "CVE-2020-14387",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}