{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Under investigation",
      "package_name": "nodejs-socket.io",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Under investigation",
      "package_name": "yarnpkg-socket.io",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-01-08T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-36049 yarnpkg-socket.io: a denial of service (memory consumption) via a large packet because a concatenation approach is used",
    "id": "1918266",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1918266"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-36049",
  "document_distribution": "",
  "details": [
    "socket.io-parser before 3.4.1 allows attackers to cause a denial of service (memory consumption) via a large packet because a concatenation approach is used."
  ],
  "references": null
}