{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-25635"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in Ansible Base when using the aws_ssm connection plugin as garbage collector is not happening after playbook run is completed. Files would remain in the bucket exposing the data. This issue affects directly data confidentiality."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25635",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25635"
        },
        {
          "name": "https://github.com/ansible-collections/community.aws/issues/222",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/ansible-collections/community.aws/issues/222"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-10-05T16:14Z",
  "publishedDate": "2020-10-05T14:15Z"
}