{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-25658"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "It was found that python-rsa is vulnerable to Bleichenbacher timing attacks. An attacker can use this flaw via the RSA decryption API to decrypt parts of the cipher text encrypted with RSA."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25658",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25658"
        },
        {
          "name": "https://github.com/sybrenstuvel/python-rsa/issues/165",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/sybrenstuvel/python-rsa/issues/165"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-11-12T15:28Z",
  "publishedDate": "2020-11-12T14:15Z"
}