{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2012-0955"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "software-properties was vulnerable to a person-in-the-middle attack due to incorrect TLS certificate validation in softwareproperties/ppa.py. software-properties didn't check TLS certificates under python2 and only checked certificates under python3 if a valid certificate bundle was provided. Fixed in software-properties version 0.92."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://code.launchpad.net/~cyphermox/software-properties/lp1036839/+merge/119753",
          "refsource": "UBUNTU",
          "tags": [],
          "url": "https://code.launchpad.net/~cyphermox/software-properties/lp1036839/+merge/119753"
        },
        {
          "name": "https://launchpad.net/bugs/1036839",
          "refsource": "UBUNTU",
          "tags": [],
          "url": "https://launchpad.net/bugs/1036839"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-12-02T01:15Z",
  "publishedDate": "2020-12-02T01:15Z"
}